config/routes.rb
Rails.application.routes.draw do

  root "finances#home"

  resources :expenses

  resources :users
  resources :user_sessions
  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  

end

app/models/concerns/expense.rb
class Expense
  include Mongoid::Document
  field :amount, type: Float
end

app/models/expense.rb
class Expense
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :tag

  field :amount, type: Float
  field :description, type: String
  field :spent_on, type: Date

end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :expenses

  field :name, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email, type: String
  field :crypted_password, type: String
  field :salt, type: String


  validates :email, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }

  authenticates_with_sorcery!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login

  def not_authenticated
    redirect_to login_url
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    
    respond_to do |format|
      if @expense.save
        format.html { redirect_to :root, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params[:expense].permit(:amount, :tag_id, :spent_on, :description)
    end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
 
  def home
    @expense = Expense.new
    @expenses = Expense.order(spent_on: :desc, created_at: :desc)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_url, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:index, :new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'Good to go! Just add your expenses.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    set_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expenses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/finances/_expense_form.html.erb
<h3> Add new expense </h3>
<%= form_for @expense do |f| %>
  <div>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :spent_on %>
    <%= f.text_field :spent_on, value: Date.today.strftime("%d-%m-%Y") %>
  </div>
  <div>
    <%= f.select :tag_id, Tag.all.map{|t| [t.name, t.id]} %> 
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/home.html.erb
<h2>Expenses</h2>

<div id="expenses-block">
  <% @expenses.each do |e| %>
  <div >
    <span class="expense">
    − <%= e.amount %>
    </span>
    |
    <%=e.spent_on%>
    |
    <%=e.tag.try(:name) %> 
    |
    <%= e.description %>
  </div>
  <% end %>
  <%= render 'expense_form' %>
</div>

<div id="login-block">
    <%= current_user.email %> | <%= link_to "Logout", logout_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <p id="notice"><%= flash[:notice] %></p>
  <p id="alert"><%= flash[:alert] %></p>
</div>

<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Not so fast, young lady</h1>
<div>
  You need to login first. 
  (Or <a href="/signup">go signup</a> if you haven't account yet)
  <%= render 'form' %>
</div>  

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create new user account</h1>
<h3>You need it to use the app</h3>
<%= render 'form' %>

<%= link_to 'Back', login_path %>